#! /bin/sh

setxkbmap us -variant colemak &
sxhkd -m -1 &
picom --experimental-backends --backend glx &
unclutter &
dunst &
wmname compiz &
polybar example &
keynav &
nitrogen --restore

bspc monitor -d code II III IV V

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
