#! /bin/sh

sxhkd -m -1 &
picom --experimental-backends --backend glx &
unclutter &
dunst &
wmname compiz &
polybar example -r &
nitrogen --restore

bspc monitor -d code browse gaming music messaging

bspc config border_width         5
bspc config window_gap           20

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#eceff4"
bspc config focused_border_color "#8fbcbb"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
